### master username: postgres, password: admin123*, db-instance: mlflowdb

In [2]:
import mlflow

In [3]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [4]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [8]:
model = LogisticRegression(solver='newton-cg', multi_class='auto')
model.fit(X_train, y_train)

LogisticRegression(solver='newton-cg')

In [19]:
model1 = LogisticRegression()

In [20]:
model1

LogisticRegression()

In [9]:
y_pred = model.predict(X_test)

# Calculate accuracy
y_true = y_test

In [10]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")

In [11]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [12]:
mlflow.create_experiment("mlflow-demoexp")

'325412397588286436'

In [14]:
mlflow.set_experiment('mlflow-demoexp')

<Experiment: artifact_location='mlflow-artifacts:/325412397588286436', creation_time=1712381414455, experiment_id='325412397588286436', last_update_time=1712381414455, lifecycle_stage='active', name='mlflow-demoexp', tags={}>

In [18]:
model

LogisticRegression(solver='newton-cg')

In [24]:

with mlflow.start_run(run_name='demo6'):
    mlflow.log_params({
           "solver":model.solver,
           "multi_class":model.multi_class
       })
    mlflow.log_param('dummy',10)
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    f1 = f1_score(y_true, y_pred, average='weighted')
    
    mlflow.log_metrics({
        "accuracy": 0.87,
        "precision": 0.5,
        "recall": 0.67
    })
    

#     # Log metrics to MLflow
#     mlflow.log_metric("accuracy", accuracy)
#     mlflow.log_metric("precision", precision)
#     mlflow.log_metric("recall", recall)
#     mlflow.log_metric("f1_score", f1)
    
    mlflow.sklearn.log_model(model,"mymodel", registered_model_name='demo-registry')



# Print the accuracy
#print(f"Accuracy: {accuracy * 100:.2f}%")

Registered model 'demo-registry' already exists. Creating a new version of this model...
2024/04/06 11:23:07 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: demo-registry, version 2
Created version '2' of model 'demo-registry'.


In [25]:
load_model = mlflow.pyfunc.load_model(f"models:/demo-registry/Production")

C:\Users\Annamalai\AppData\Roaming\Python\Python39\site-packages\mlflow\store\artifact\utils\models.py:32: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/2.11.3/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])


In [26]:
load_model.predict(X_test)

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 1, 2, 1, 2, 1, 1, 2,
       0, 1, 1, 0, 0, 0, 2, 1])

In [27]:
from mlflow import MlflowClient
client = MlflowClient()

model = client.get_latest_versions('demo-registry',['Production'])[0]
source_uri = model.source
model3 = mlflow.pyfunc.load_model(source_uri)

C:\Users\ANNAMA~1\AppData\Local\Temp/ipykernel_10816/1615667432.py:4: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/2.11.3/model-registry.html#migrating-from-stages
  model = client.get_latest_versions('demo-registry',['Production'])[0]


In [28]:
source_uri

'mlflow-artifacts:/325412397588286436/eb46bc9695d745f4b7c4dc2aad57fd20/artifacts/mymodel'

In [32]:
demo = mlflow.pyfunc.load_model(model.source)

In [33]:
demo.predict(X_test)

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 1, 2, 1, 2, 1, 1, 2,
       0, 1, 1, 0, 0, 0, 2, 1])